src: 
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.de-en.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.de-es.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.en-de.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.en-es.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.es-de.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.es-en.es
tgt: 
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.de-en.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.de-es.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.en-de.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.en-es.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.es-de.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/train.es-en.en
domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
eval_src:
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.de-en.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.de-es.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.en-de.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.en-es.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.es-de.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.es-en.es

eval_ref:
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.de-en.en
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.de-es.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.en-de.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.en-es.es
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.es-de.de
        - /share3/users/quang/data/multilingual/train_dev_test_tok/spm_tok/temp/dev.es-en.en

eval_domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

src_vocab: /home/minhquang.pham/Latent-group-dropout/vocab/m2m11.spm.vocab
tgt_vocab: /home/minhquang.pham/Latent-group-dropout/vocab/m2m11.spm.vocab

model_dir: /share3/users/quang/models/multilingual/lamgd

batch_train_size: 3072
batch_type: tokens
experiment: TopK_Sparse_Layers_multi_layer
num_units: 512
num_heads: 8
ffn_inner_dim: 2048
dropout: 0.1
ffn_dropout: 0.1
attention_dropout: 0.1
version: 2
accumulation_step: 1
train_steps: 300000
num_domain_unit_group: 16
num_shared_units: 0
unit_group_size: 32
domain_group_allocation_num: 12
gumbel_temperature_decay: 1000
r_coeff: 0.00005
kl_coeff: 0.0001
latent_logit_lr: 0.001
min_temperature: 0.2
start_temperature: 0.2
step_duration: 8
save_every: 5000
eval_every: 10000
num_domains: 20
num_inspected_domains: 6
picking_prob: Natural
temperature: 1.0
learning_rate: 1.0
