src: 
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.train.en
tgt: 
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.train.fr
domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
eval_src:
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.dev.en

eval_ref:
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.dev.fr

eval_domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

src_vocab: /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/vocab.en_fr
tgt_vocab: /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/vocab.en_fr

model_dir: /gpfsdsstore/projects/rech/sfz/utt84zy/models/config_1365

batch_train_size: 3072
batch_meta_train_size: 3072
batch_meta_test_size: 3072
batch_type: tokens
experiment: TopK_Sparse_Layers_multi_layer
num_units: 512
num_heads: 8
ffn_inner_dim: 2048
dropout: 0.1
ffn_dropout: 0.1
attention_dropout: 0.1
version: 2
accumulation_step: 1
train_steps: 300000
num_domain_unit_group: 16
num_shared_units: 0
unit_group_size: 32
domain_group_allocation_num: 12
gumbel_temperature_decay: 1000
r_coeff: 0.00005
kl_coeff: 0.0001
latent_logit_lr: 0.001
min_temperature: 0.2
start_temperature: 0.2
step_duration: 8
save_every: 5000
eval_every: 10000
num_domains: 20
num_inspected_domains: 6
picking_prob: Natural
temperature: 1.0
learning_rate: 1.0
