apiVersion: batch/v1
kind: Job
metadata:
    name: quang-lamgd-train
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: share3
        nfs:
          server: 10.20.44.66
          path: "/export/kites_team"
      containers:
      - args:
         ["/bin/bash", "-c",
         "python3 -u practice.py train_elbo_topK_sparse_layer_multi_layer --config /share3/users/quang/workspace/Latent-group-dropout/configs/config_1365.yml"
         ]
        name: fairseq-container
        image: registry.zoomdev.us/languagetech/sc-fairseq:LaMGD-dev
        imagePullPolicy: Always
        stdin: true
        resources:
          limits:
            nvidia.com/gpu: "2"
        volumeMounts:
        - name: share3
          mountPath: /share3
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
  backoffLimit: 1
